In [2]:
import polars as pl



#load the data from season 2023
pbp = pl.read_parquet("../data/pbp_2023.parquet")

In [4]:
print(pbp.columns)

['play_id', 'game_id', 'old_game_id', 'home_team', 'away_team', 'season_type', 'week', 'posteam', 'posteam_type', 'defteam', 'side_of_field', 'yardline_100', 'game_date', 'quarter_seconds_remaining', 'half_seconds_remaining', 'game_seconds_remaining', 'game_half', 'quarter_end', 'drive', 'sp', 'qtr', 'down', 'goal_to_go', 'time', 'yrdln', 'ydstogo', 'ydsnet', 'desc', 'play_type', 'yards_gained', 'shotgun', 'no_huddle', 'qb_dropback', 'qb_kneel', 'qb_spike', 'qb_scramble', 'pass_length', 'pass_location', 'air_yards', 'yards_after_catch', 'run_location', 'run_gap', 'field_goal_result', 'kick_distance', 'extra_point_result', 'two_point_conv_result', 'home_timeouts_remaining', 'away_timeouts_remaining', 'timeout', 'timeout_team', 'td_team', 'td_player_name', 'td_player_id', 'posteam_timeouts_remaining', 'defteam_timeouts_remaining', 'total_home_score', 'total_away_score', 'posteam_score', 'defteam_score', 'score_differential', 'posteam_score_post', 'defteam_score_post', 'score_differential_post', 'no_score_prob', 'opp_fg_prob', 'opp_safety_prob', 'opp_td_prob', 'fg_prob', 'safety_prob', 'td_prob', 'extra_point_prob', 'two_point_conversion_prob', 'ep', 'epa', 'total_home_epa', 'total_away_epa', 'total_home_rush_epa', 'total_away_rush_epa', 'total_home_pass_epa', 'total_away_pass_epa', 'air_epa', 'yac_epa', 'comp_air_epa', 'comp_yac_epa', 'total_home_comp_air_epa', 'total_away_comp_air_epa', 'total_home_comp_yac_epa', 'total_away_comp_yac_epa', 'total_home_raw_air_epa', 'total_away_raw_air_epa', 'total_home_raw_yac_epa', 'total_away_raw_yac_epa', 'wp', 'def_wp', 'home_wp', 'away_wp', 'wpa', 'vegas_wpa', 'vegas_home_wpa', 'home_wp_post', 'away_wp_post', 'vegas_wp', 'vegas_home_wp', 'total_home_rush_wpa', 'total_away_rush_wpa', 'total_home_pass_wpa', 'total_away_pass_wpa', 'air_wpa', 'yac_wpa', 'comp_air_wpa', 'comp_yac_wpa', 'total_home_comp_air_wpa', 'total_away_comp_air_wpa', 'total_home_comp_yac_wpa', 'total_away_comp_yac_wpa', 'total_home_raw_air_wpa', 'total_away_raw_air_wpa', 'total_home_raw_yac_wpa', 'total_away_raw_yac_wpa', 'punt_blocked', 'first_down_rush', 'first_down_pass', 'first_down_penalty', 'third_down_converted', 'third_down_failed', 'fourth_down_converted', 'fourth_down_failed', 'incomplete_pass', 'touchback', 'interception', 'punt_inside_twenty', 'punt_in_endzone', 'punt_out_of_bounds', 'punt_downed', 'punt_fair_catch', 'kickoff_inside_twenty', 'kickoff_in_endzone', 'kickoff_out_of_bounds', 'kickoff_downed', 'kickoff_fair_catch', 'fumble_forced', 'fumble_not_forced', 'fumble_out_of_bounds', 'solo_tackle', 'safety', 'penalty', 'tackled_for_loss', 'fumble_lost', 'own_kickoff_recovery', 'own_kickoff_recovery_td', 'qb_hit', 'rush_attempt', 'pass_attempt', 'sack', 'touchdown', 'pass_touchdown', 'rush_touchdown', 'return_touchdown', 'extra_point_attempt', 'two_point_attempt', 'field_goal_attempt', 'kickoff_attempt', 'punt_attempt', 'fumble', 'complete_pass', 'assist_tackle', 'lateral_reception', 'lateral_rush', 'lateral_return', 'lateral_recovery', 'passer_player_id', 'passer_player_name', 'passing_yards', 'receiver_player_id', 'receiver_player_name', 'receiving_yards', 'rusher_player_id', 'rusher_player_name', 'rushing_yards', 'lateral_receiver_player_id', 'lateral_receiver_player_name', 'lateral_receiving_yards', 'lateral_rusher_player_id', 'lateral_rusher_player_name', 'lateral_rushing_yards', 'lateral_sack_player_id', 'lateral_sack_player_name', 'interception_player_id', 'interception_player_name', 'lateral_interception_player_id', 'lateral_interception_player_name', 'punt_returner_player_id', 'punt_returner_player_name', 'lateral_punt_returner_player_id', 'lateral_punt_returner_player_name', 'kickoff_returner_player_name', 'kickoff_returner_player_id', 'lateral_kickoff_returner_player_id', 'lateral_kickoff_returner_player_name', 'punter_player_id', 'punter_player_name', 'kicker_player_name', 'kicker_player_id', 'own_kickoff_recovery_player_id', 'own_kickoff_recovery_player_name', 'blocked_player_id', 'blocked_player_name', 'tackle_for_loss_1_player_id', 'tackle_for_loss_1_player_name', 'tackle_for_loss_2_player_id', 'tackle_for_loss_2_player_name', 'qb_hit_1_player_id', 'qb_hit_1_player_name', 'qb_hit_2_player_id', 'qb_hit_2_player_name', 'forced_fumble_player_1_team', 'forced_fumble_player_1_player_id', 'forced_fumble_player_1_player_name', 'forced_fumble_player_2_team', 'forced_fumble_player_2_player_id', 'forced_fumble_player_2_player_name', 'solo_tackle_1_team', 'solo_tackle_2_team', 'solo_tackle_1_player_id', 'solo_tackle_2_player_id', 'solo_tackle_1_player_name', 'solo_tackle_2_player_name', 'assist_tackle_1_player_id', 'assist_tackle_1_player_name', 'assist_tackle_1_team', 'assist_tackle_2_player_id', 'assist_tackle_2_player_name', 'assist_tackle_2_team', 'assist_tackle_3_player_id', 'assist_tackle_3_player_name', 'assist_tackle_3_team', 'assist_tackle_4_player_id', 'assist_tackle_4_player_name', 'assist_tackle_4_team', 'tackle_with_assist', 'tackle_with_assist_1_player_id', 'tackle_with_assist_1_player_name', 'tackle_with_assist_1_team', 'tackle_with_assist_2_player_id', 'tackle_with_assist_2_player_name', 'tackle_with_assist_2_team', 'pass_defense_1_player_id', 'pass_defense_1_player_name', 'pass_defense_2_player_id', 'pass_defense_2_player_name', 'fumbled_1_team', 'fumbled_1_player_id', 'fumbled_1_player_name', 'fumbled_2_player_id', 'fumbled_2_player_name', 'fumbled_2_team', 'fumble_recovery_1_team', 'fumble_recovery_1_yards', 'fumble_recovery_1_player_id', 'fumble_recovery_1_player_name', 'fumble_recovery_2_team', 'fumble_recovery_2_yards', 'fumble_recovery_2_player_id', 'fumble_recovery_2_player_name', 'sack_player_id', 'sack_player_name', 'half_sack_1_player_id', 'half_sack_1_player_name', 'half_sack_2_player_id', 'half_sack_2_player_name', 'return_team', 'return_yards', 'penalty_team', 'penalty_player_id', 'penalty_player_name', 'penalty_yards', 'replay_or_challenge', 'replay_or_challenge_result', 'penalty_type', 'defensive_two_point_attempt', 'defensive_two_point_conv', 'defensive_extra_point_attempt', 'defensive_extra_point_conv', 'safety_player_name', 'safety_player_id', 'season', 'cp', 'cpoe', 'series', 'series_success', 'series_result', 'order_sequence', 'start_time', 'time_of_day', 'stadium', 'weather', 'nfl_api_id', 'play_clock', 'play_deleted', 'play_type_nfl', 'special_teams_play', 'st_play_type', 'end_clock_time', 'end_yard_line', 'fixed_drive', 'fixed_drive_result', 'drive_real_start_time', 'drive_play_count', 'drive_time_of_possession', 'drive_first_downs', 'drive_inside20', 'drive_ended_with_score', 'drive_quarter_start', 'drive_quarter_end', 'drive_yards_penalized', 'drive_start_transition', 'drive_end_transition', 'drive_game_clock_start', 'drive_game_clock_end', 'drive_start_yard_line', 'drive_end_yard_line', 'drive_play_id_started', 'drive_play_id_ended', 'away_score', 'home_score', 'location', 'result', 'total', 'spread_line', 'total_line', 'div_game', 'roof', 'surface', 'temp', 'wind', 'home_coach', 'away_coach', 'stadium_id', 'game_stadium', 'aborted_play', 'success', 'passer', 'passer_jersey_number', 'rusher', 'rusher_jersey_number', 'receiver', 'receiver_jersey_number', 'pass', 'rush', 'first_down', 'special', 'play', 'passer_id', 'rusher_id', 'receiver_id', 'name', 'jersey_number', 'id', 'fantasy_player_name', 'fantasy_player_id', 'fantasy', 'fantasy_id', 'out_of_bounds', 'home_opening_kickoff', 'qb_epa', 'xyac_epa', 'xyac_mean_yardage', 'xyac_median_yardage', 'xyac_success', 'xyac_fd', 'xpass', 'pass_oe']

In [8]:
cols = ["game_id", "home_team", "away_team", "posteam", "score_differential", "game_seconds_remaining", "down", "ydstogo","result"]
pbp.select(cols).head(20)

shape: (20, 9)
┌─────────────────┬───────────┬───────────┬─────────┬───┬────────────────┬──────┬─────────┬────────┐
│ game_id         ┆ home_team ┆ away_team ┆ posteam ┆ … ┆ game_seconds_r ┆ down ┆ ydstogo ┆ result │
│ ---             ┆ ---       ┆ ---       ┆ ---     ┆   ┆ emaining       ┆ ---  ┆ ---     ┆ ---    │
│ str             ┆ str       ┆ str       ┆ str     ┆   ┆ ---            ┆ f64  ┆ f64     ┆ i32    │
│                 ┆           ┆           ┆         ┆   ┆ f64            ┆      ┆         ┆        │
╞═════════════════╪═══════════╪═══════════╪═════════╪═══╪════════════════╪══════╪═════════╪════════╡
│ 2023_01_ARI_WAS ┆ WAS       ┆ ARI       ┆ null    ┆ … ┆ 3600.0         ┆ null ┆ 0.0     ┆ 4      │
│ 2023_01_ARI_WAS ┆ WAS       ┆ ARI       ┆ WAS     ┆ … ┆ 3600.0         ┆ null ┆ 0.0     ┆ 4      │
│ 2023_01_ARI_WAS ┆ WAS       ┆ ARI       ┆ WAS     ┆ … ┆ 3600.0         ┆ 1.0  ┆ 10.0    ┆ 4      │
│ 2023_01_ARI_WAS ┆ WAS       ┆ ARI       ┆ WAS     ┆ … ┆ 3570.0         ┆ 2.0  ┆ 7.0     ┆ 4      │
│ 2023_01_ARI_WAS ┆ WAS       ┆ ARI       ┆ WAS     ┆ … ┆ 3535.0         ┆ 3.0  ┆ 1.0     ┆ 4      │
│ …               ┆ …         ┆ …         ┆ …       ┆ … ┆ …              ┆ …    ┆ …       ┆ …      │
│ 2023_01_ARI_WAS ┆ WAS       ┆ ARI       ┆ ARI     ┆ … ┆ 3248.0         ┆ 2.0  ┆ 10.0    ┆ 4      │
│ 2023_01_ARI_WAS ┆ WAS       ┆ ARI       ┆ ARI     ┆ … ┆ 3208.0         ┆ 3.0  ┆ 13.0    ┆ 4      │
│ 2023_01_ARI_WAS ┆ WAS       ┆ ARI       ┆ ARI     ┆ … ┆ 3165.0         ┆ 4.0  ┆ 8.0     ┆ 4      │
│ 2023_01_ARI_WAS ┆ WAS       ┆ ARI       ┆ WAS     ┆ … ┆ 3155.0         ┆ 1.0  ┆ 10.0    ┆ 4      │
│ 2023_01_ARI_WAS ┆ WAS       ┆ ARI       ┆ WAS     ┆ … ┆ 3131.0         ┆ 1.0  ┆ 10.0    ┆ 4      │
└─────────────────┴───────────┴───────────┴─────────┴───┴────────────────┴──────┴─────────┴────────┘

In [9]:
pbp["game_id"].n_unique()
pbp["game_id"].unique().sort()

shape: (285,)
Series: 'game_id' [str]
[
	"2023_01_ARI_WAS"
	"2023_01_BUF_NYJ"
	"2023_01_CAR_ATL"
	"2023_01_CIN_CLE"
	"2023_01_DAL_NYG"
	…
	"2023_20_KC_BUF"
	"2023_20_TB_DET"
	"2023_21_DET_SF"
	"2023_21_KC_BAL"
	"2023_22_SF_KC"
]

In [11]:
pbp.filter(pl.col("posteam").is_null()).select(cols + ["desc"]).head(20)

shape: (20, 10)
┌─────────────────┬───────────┬───────────┬─────────┬───┬──────┬─────────┬────────┬────────────────┐
│ game_id         ┆ home_team ┆ away_team ┆ posteam ┆ … ┆ down ┆ ydstogo ┆ result ┆ desc           │
│ ---             ┆ ---       ┆ ---       ┆ ---     ┆   ┆ ---  ┆ ---     ┆ ---    ┆ ---            │
│ str             ┆ str       ┆ str       ┆ str     ┆   ┆ f64  ┆ f64     ┆ i32    ┆ str            │
╞═════════════════╪═══════════╪═══════════╪═════════╪═══╪══════╪═════════╪════════╪════════════════╡
│ 2023_01_ARI_WAS ┆ WAS       ┆ ARI       ┆ null    ┆ … ┆ null ┆ 0.0     ┆ 4      ┆ GAME           │
│ 2023_01_ARI_WAS ┆ WAS       ┆ ARI       ┆ null    ┆ … ┆ null ┆ 0.0     ┆ 4      ┆ Timeout #1 by  │
│                 ┆           ┆           ┆         ┆   ┆      ┆         ┆        ┆ ARI at 01:43.  │
│ 2023_01_ARI_WAS ┆ WAS       ┆ ARI       ┆ null    ┆ … ┆ null ┆ 0.0     ┆ 4      ┆ Timeout #1 by  │
│                 ┆           ┆           ┆         ┆   ┆      ┆         ┆        ┆ WAS at 01:55.  │
│ 2023_01_ARI_WAS ┆ WAS       ┆ ARI       ┆ null    ┆ … ┆ null ┆ 0.0     ┆ 4      ┆ Timeout #2 by  │
│                 ┆           ┆           ┆         ┆   ┆      ┆         ┆        ┆ WAS at 01:41.  │
│ 2023_01_ARI_WAS ┆ WAS       ┆ ARI       ┆ null    ┆ … ┆ null ┆ 0.0     ┆ 4      ┆ Timeout #3 by  │
│                 ┆           ┆           ┆         ┆   ┆      ┆         ┆        ┆ WAS at 00:19.  │
│ …               ┆ …         ┆ …         ┆ …       ┆ … ┆ …    ┆ …       ┆ …      ┆ …              │
│ 2023_01_BUF_NYJ ┆ NYJ       ┆ BUF       ┆ null    ┆ … ┆ null ┆ 0.0     ┆ 6      ┆ Timeout #2 by  │
│                 ┆           ┆           ┆         ┆   ┆      ┆         ┆        ┆ BUF at 01:51.  │
│ 2023_01_BUF_NYJ ┆ NYJ       ┆ BUF       ┆ null    ┆ … ┆ null ┆ 0.0     ┆ 6      ┆ Timeout #1 by  │
│                 ┆           ┆           ┆         ┆   ┆      ┆         ┆        ┆ NYJ at 00:35.  │
│ 2023_01_BUF_NYJ ┆ NYJ       ┆ BUF       ┆ null    ┆ … ┆ null ┆ 0.0     ┆ 6      ┆ Timeout #3 by  │
│                 ┆           ┆           ┆         ┆   ┆      ┆         ┆        ┆ BUF at 00:29.  │
│ 2023_01_BUF_NYJ ┆ NYJ       ┆ BUF       ┆ null    ┆ … ┆ null ┆ 0.0     ┆ 6      ┆ Timeout #2 by  │
│                 ┆           ┆           ┆         ┆   ┆      ┆         ┆        ┆ NYJ at 00:10.  │
│ 2023_01_BUF_NYJ ┆ NYJ       ┆ BUF       ┆ null    ┆ … ┆ null ┆ 0.0     ┆ 6      ┆ END QUARTER 4  │
└─────────────────┴───────────┴───────────┴─────────┴───┴──────┴─────────┴────────┴────────────────┘

In [ ]:
plays = pbp.filter(pl.col("posteam").is_not_null())

print(pbp.height - plays.height) #checkow how many rows I dropped

2638

In [22]:
plays = plays.filter(pl.col("result") != 0)

#see if the team with postion won
home_won = (pl.col("posteam") == pl.col("home_team")) & (pl.col("result") > 0)
away_won = (pl.col("posteam") == pl.col("away_team")) & (pl.col("result") < 0) #result is calc home score - away score so pos means home won, neg means away team won
plays = plays.with_columns(
    pl.when(home_won | away_won).then(1).otherwise(0).alias("posteam_won")
)

plays.select(["game_id", "home_team", "away_team", "posteam", "result", "posteam_won"]).head(20)
plays["posteam_won"].mean()

0.5054330490994535

In [23]:
features = ["score_differential", "game_seconds_remaining", "down", "ydstogo",
            "yardline_100", "posteam_timeouts_remaining", "defteam_timeouts_remaining"]
plays.select(features).null_count()

shape: (1, 7)
┌────────────────┬────────────────┬──────┬─────────┬──────────────┬────────────────┬───────────────┐
│ score_differen ┆ game_seconds_r ┆ down ┆ ydstogo ┆ yardline_100 ┆ posteam_timeou ┆ defteam_timeo │
│ tial           ┆ emaining       ┆ ---  ┆ ---     ┆ ---          ┆ ts_remaining   ┆ uts_remaining │
│ ---            ┆ ---            ┆ u32  ┆ u32     ┆ u32          ┆ ---            ┆ ---           │
│ u32            ┆ u32            ┆      ┆         ┆              ┆ u32            ┆ u32           │
╞════════════════╪════════════════╪══════╪═════════╪══════════════╪════════════════╪═══════════════╡
│ 0              ┆ 5              ┆ 5102 ┆ 0       ┆ 847          ┆ 0              ┆ 0             │
└────────────────┴────────────────┴──────┴─────────┴──────────────┴────────────────┴───────────────┘

In [24]:
plays.filter(pl.col("down").is_null()).select(features + ["play_type", "desc"]).head(20)

shape: (20, 9)
┌────────────┬────────────┬──────┬─────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ score_diff ┆ game_secon ┆ down ┆ ydstogo ┆ … ┆ posteam_ti ┆ defteam_ti ┆ play_type  ┆ desc       │
│ erential   ┆ ds_remaini ┆ ---  ┆ ---     ┆   ┆ meouts_rem ┆ meouts_rem ┆ ---        ┆ ---        │
│ ---        ┆ ng         ┆ f64  ┆ f64     ┆   ┆ aining     ┆ aining     ┆ str        ┆ str        │
│ f64        ┆ ---        ┆      ┆         ┆   ┆ ---        ┆ ---        ┆            ┆            │
│            ┆ f64        ┆      ┆         ┆   ┆ f64        ┆ f64        ┆            ┆            │
╞════════════╪════════════╪══════╪═════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ 0.0        ┆ 3600.0     ┆ null ┆ 0.0     ┆ … ┆ 3.0        ┆ 3.0        ┆ kickoff    ┆ 5-M.Prater │
│            ┆            ┆      ┆         ┆   ┆            ┆            ┆            ┆ kicks 65   │
│            ┆            ┆      ┆         ┆   ┆            ┆            ┆            ┆ yards      │
│            ┆            ┆      ┆         ┆   ┆            ┆            ┆            ┆ from…      │
│ 6.0        ┆ 2955.0     ┆ null ┆ 0.0     ┆ … ┆ 3.0        ┆ 3.0        ┆ extra_poin ┆ 6-J.Slye   │
│            ┆            ┆      ┆         ┆   ┆            ┆            ┆ t          ┆ extra      │
│            ┆            ┆      ┆         ┆   ┆            ┆            ┆            ┆ point is   │
│            ┆            ┆      ┆         ┆   ┆            ┆            ┆            ┆ GOOD, …    │
│ -7.0       ┆ 2955.0     ┆ null ┆ 0.0     ┆ … ┆ 3.0        ┆ 3.0        ┆ kickoff    ┆ 6-J.Slye   │
│            ┆            ┆      ┆         ┆   ┆            ┆            ┆            ┆ kicks 65   │
│            ┆            ┆      ┆         ┆   ┆            ┆            ┆            ┆ yards from │
│            ┆            ┆      ┆         ┆   ┆            ┆            ┆            ┆ W…         │
│ 4.0        ┆ 2753.0     ┆ null ┆ 0.0     ┆ … ┆ 3.0        ┆ 2.0        ┆ kickoff    ┆ 5-M.Prater │
│            ┆            ┆      ┆         ┆   ┆            ┆            ┆            ┆ kicks 65   │
│            ┆            ┆      ┆         ┆   ┆            ┆            ┆            ┆ yards      │
│            ┆            ┆      ┆         ┆   ┆            ┆            ┆            ┆ from…      │
│ 4.0        ┆ 2700.0     ┆ null ┆ 0.0     ┆ … ┆ 3.0        ┆ 2.0        ┆ null       ┆ END        │
│            ┆            ┆      ┆         ┆   ┆            ┆            ┆            ┆ QUARTER 1  │
│ …          ┆ …          ┆ …    ┆ …       ┆ … ┆ …          ┆ …          ┆ …          ┆ …          │
│ 0.0        ┆ 3600.0     ┆ null ┆ 0.0     ┆ … ┆ 3.0        ┆ 3.0        ┆ kickoff    ┆ 9-G.Zuerle │
│            ┆            ┆      ┆         ┆   ┆            ┆            ┆            ┆ in kicks   │
│            ┆            ┆      ┆         ┆   ┆            ┆            ┆            ┆ 65 yards   │
│            ┆            ┆      ┆         ┆   ┆            ┆            ┆            ┆ fr…        │
│ -3.0       ┆ 2885.0     ┆ null ┆ 0.0     ┆ … ┆ 3.0        ┆ 3.0        ┆ kickoff    ┆ 2-T.Bass   │
│            ┆            ┆      ┆         ┆   ┆            ┆            ┆            ┆ kicks 61   │
│            ┆            ┆      ┆         ┆   ┆            ┆            ┆            ┆ yards from │
│            ┆            ┆      ┆         ┆   ┆            ┆            ┆            ┆ B…         │
│ -3.0       ┆ 2700.0     ┆ null ┆ 0.0     ┆ … ┆ 3.0        ┆ 3.0        ┆ null       ┆ END        │
│            ┆            ┆      ┆         ┆   ┆            ┆            ┆            ┆ QUARTER 1  │
│ 0.0        ┆ 2435.0     ┆ null ┆ 0.0     ┆ … ┆ 3.0        ┆ 3.0        ┆ kickoff    ┆ 9-G.Zuerle │
│            ┆            ┆      ┆         ┆   ┆            ┆            ┆            ┆ in kicks   │
│            ┆            ┆      ┆         ┆   ┆            ┆            ┆            ┆ 65 yards   │
│            ┆            ┆      ┆         ┆   ┆            ┆            ┆            ┆ fr…        │
│ 6.0        ┆ 2083.0     ┆ null ┆ 0.0     ┆ … ┆ 3.0        ┆ 3.0        ┆ extra_poin ┆ 2-T.Bass   │
│            ┆            ┆      ┆         ┆   ┆            ┆            ┆ t          ┆ extra      │
│            ┆            ┆      ┆         ┆   ┆            ┆            ┆            ┆ point is   │
│            ┆            ┆      ┆         ┆   ┆            ┆            ┆            ┆ GOOD, …    │
└────────────┴────────────┴──────┴─────────┴───┴────────────┴────────────┴────────────┴────────────┘

In [25]:
plays = plays.drop_nulls(subset=features)
plays.select(features).null_count()
print(plays.height)

41925

Basically, I have dropped null values inside the set of features for features like "down" "yardline_100" "game_seconds_renaming". "down" had a lot of nulls due to kickoffs, extra points, anything that isnt a play from scrimmage. In addition I also cleaned data where thier were no rows with posteam, because my model focuses on real time data, so not knowing who has pocession is harmful.